# Generated by Django 2.1.11 on 2022-04-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.TextField(default='https://res.cloudinary.com/dxsy9rszs/image/upload/v1650449869/raisinpoire_dytmdo.png', verbose_name='imagelink'),
            preserve_default=False,
        ),
    ]
