# Generated by Django 2.1.11 on 2022-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.CharField(default='https://res.cloudinary.com/dxsy9rszs/image/upload/v1650536254/vinFichier_12_cyagkz.png', max_length=10000, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
