# Generated by Django 4.0.4 on 2022-06-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='correcting_factor_activated',
            field=models.BooleanField(default=True, verbose_name='Activation du facteur de correction'),
        ),
    ]
