# Generated by Django 4.0.4 on 2022-06-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_category_category_image_category_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorsalemodule',
            name='ask_password',
            field=models.BooleanField(default=False, verbose_name='Demande du mot de passe'),
        ),
    ]
