# Generated by Django 4.0.4 on 2023-08-31 22:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(
                    default=django.utils.timezone.now, verbose_name='Date')),
                ('billamount', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[
                 django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant de la facture')),
                ('operator', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
        ),
    ]
